"""initial schema

Revision ID: 1b822f0d2f36
Revises: 
Create Date: 2026-08-28 23:03:50.640181

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1b822f0d2f36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_local', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialects_name'), 'dialects', ['name'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headword_devanagari', sa.String(length=200), nullable=False),
    sa.Column('headword_roman', sa.String(length=200), nullable=True),
    sa.Column('headword_ipa', sa.String(length=300), nullable=True),
    sa.Column('headword_tamyig', sa.String(length=200), nullable=True),
    sa.Column('tone', sa.String(length=10), nullable=True),
    sa.Column('pos', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_headword_devanagari'), 'entries', ['headword_devanagari'], unique=False)
    op.create_index(op.f('ix_entries_headword_roman'), 'entries', ['headword_roman'], unique=False)
    op.create_index(op.f('ix_entries_status'), 'entries', ['status'], unique=False)
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('definition_devanagari', sa.String(), nullable=False),
    sa.Column('definition_roman', sa.String(), nullable=True),
    sa.Column('gloss', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.Column('text_devanagari', sa.String(), nullable=True),
    sa.Column('text_roman', sa.String(), nullable=True),
    sa.Column('translation_devanagari', sa.String(), nullable=True),
    sa.Column('translation_english', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examples')
    op.drop_table('senses')
    op.drop_table('audio')
    op.drop_index(op.f('ix_entries_status'), table_name='entries')
    op.drop_index(op.f('ix_entries_headword_roman'), table_name='entries')
    op.drop_index(op.f('ix_entries_headword_devanagari'), table_name='entries')
    op.drop_table('entries')
    op.drop_table('sources')
    op.drop_index(op.f('ix_dialects_name'), table_name='dialects')
    op.drop_table('dialects')
    # ### end Alembic commands ###
