"""phase 4 rich features: grammar, example glosses, wordforms

Revision ID: 40b26a9b471b
Revises: 1b822f0d2f36
Create Date: 2026-09-09 23:03:18.680227

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '40b26a9b471b'
down_revision = '1b822f0d2f36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('form_devanagari', sa.String(length=200), nullable=False),
    sa.Column('form_roman', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example_glosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('gloss', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['examples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entries', sa.Column('grammar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'grammar')
    op.drop_table('example_glosses')
    op.drop_table('wordforms')
    # ### end Alembic commands ###
