"""phase 5: etymology column, semantic groups

Revision ID: 8087f4150c2e
Revises: 40b26a9b471b
Create Date: 2026-09-09 23:11:38.314293

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8087f4150c2e'
down_revision = '40b26a9b471b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_groups_name'), 'semantic_groups', ['name'], unique=True)
    op.create_table('entry_groups',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['semantic_groups.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'group_id')
    )
    op.add_column('entries', sa.Column('etymology', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'etymology')
    op.drop_table('entry_groups')
    op.drop_index(op.f('ix_semantic_groups_name'), table_name='semantic_groups')
    op.drop_table('semantic_groups')
    # ### end Alembic commands ###
